language: r

sudo: required

apt_packages:
  - texlive
  - ghostscript
  - texlive-fonts-extra
  - texinfo  
  - bedtools
  - slurm-llnl 
#slurm-wlm does not exist on ubuntu 14.04

env:
  - TEST_SUITE=pipeline-noinput
  - TEST_SUITE=pipeline-input
  - TEST_SUITE=CRAN
  - TEST_SUITE=OTHER

script:
  - mkdir bin
  - pushd bin
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bigWigInfo
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bigWigToBedGraph
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed
  - curl -OL http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedGraphToBigWig
  - chmod 755 *
  - export PATH=$(pwd):$PATH
  - popd
  - sudo cp slurm.conf /etc/slurm-llnl
  - cp batchtools.conf.R tests/testthat
  - sudo service munge start
  - sudo /etc/init.d/slurmctld restart
  - sudo /etc/init.d/slurmd restart
  - sinfo
  - R CMD INSTALL .
  - if [ "$TEST_SUITE" == "CRAN" ];then bash build.sh;else Rscript -e "source('tests/testthat.R', chdir = TRUE)";fi

after_failure:
  - travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

